var __cat_js_path = window._cat_jspath;
var __cat_js=[];
var __cq_var = {};  //variable generated by CQ

// DEBUG FUNCTION
(function(){

    var foo = function(){};
    if(!window.console) {
        window.console = {};
    }
    var m = ["log","info","warn","error","debug"];
    //define undefined methods as noops to prevent errors
    for (var i = 0; i < m.length; i++) {
        if (!window.console[m[i]]) {
            window.console[m[i]] = foo;
        }
    }
})();

var jsFiles = [
  __cat_js_path + "/lib/jquery-1.9.1.min.js",
  __cat_js_path + "/lib/underscore.min.js",
  __cat_js_path + "/lib/backbone.min.js",
  __cat_js_path + "/lib/backbone.paginator.min.js",
  __cat_js_path + "/lib/jquery.throttledresize.min.js",
  __cat_js_path + "/lib/jquery.placeholder.min.js",
  __cat_js_path + "/lib/jquery.rz.tabify.min.js",
  __cat_js_path + "/lib/jquery.equalHeight.min.js",
  __cat_js_path + "/lib/jquery.ui.min.js",
  __cat_js_path + "/lib/bootstrap-datepicker.min.js",
  __cat_js_path + "/lib/jquery.fitvids.min.js",
  __cat_js_path + "/lib/swfobject.min.js",
  __cat_js_path + "/lib/bootstrap-tooltip.min.js",
  __cat_js_path + "/lib/bootstrap-transitions.min.js",
  __cat_js_path + "/lib/bootstrap-collapse.min.js",
  __cat_js_path + "/lib/bootstrap-dropdown.min.js",
  __cat_js_path + "/lib/bootstrap-affix.min.js",
  __cat_js_path + "/lib/bootstrap-modal.min.js",
  __cat_js_path + "/lib/elqAsynch.js",
  __cat_js_path + "/lib/amplify.min.js",
  __cat_js_path + "/global.min.js" //DO NOT CHANGE THIS LINE
];

if (head.browser && head.browser.ie && head.browser.version < 10) {
    jsFiles.push(__cat_js_path + "/lib/autocolumn.min.js");
    //jsFiles.push(__cat_js_path + "/lib/selectivizr.min.js");
}

head.load(jsFiles);